# Generated by Django 6.0.1 on 2026-01-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('village_quartier', models.CharField(max_length=255)),
                ('domaine_participation', models.CharField(choices=[('economie', 'Développement économique'), ('education', 'Éducation et Formation'), ('sante', 'Santé et Bien-être'), ('environnement', 'Environnement et Durabilité'), ('cohesion', 'Cohésion Sociale'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('motivations', models.TextField(blank=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('valide', 'Validé'), ('attente', 'En attente de validation'), ('refuse', 'Refusé')], default='nouveau', max_length=20)),
                ('consentement_rgpd', models.BooleanField(default=False)),
                ('consentement_newsletter', models.BooleanField(default=False)),
                ('date_consentement', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Adhésion',
                'verbose_name_plural': 'Adhésions',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
